name:deploy myblog

on:
  push:
    branches:
      - 'master' #针对 master 分支
    path:
      - '.github/workflows/*'
      - 'src/**'
jobs:
  deploy:
    runs-on:ubuntu-latest
    steps:
      - uses:actions/checkout@v2 #第三方的 action
      - name:create a folder 
        run:mkdir test-folder
      - name:create a file
        run:|
          cd src
          touch a.txt
          echo "hello world" > a.txt
      - name delete  a file
        run :rm -rf a.txt
